#!/bin/bash
API_URL=""
TOKEN=5
#
# while getopts ":H:t:" opt; do
#   case $opt in
#     H)     host=$OPTARG             ;;
#     t)     timeout=$OPTARG          ;;
#   esac
# done

case "$1" in

"start")  echo "Starting Monitoring service checking."
    echo -SIGHUP $2
    ;;
"stop")  echo  "Stopping Monitoring service checking."
    echo -SIGINT $2
    ;;
"reload")  echo  "Reloading services."
    echo -SIGQUIT $2
    ;;
"list") echo  "Listing services."
   ;;
*) echo "Command $1 is not processed"
   ;;
esac

exit 0
raw=$(timeout $timeout curl --write-out "%{http_code}\n" -m $timeout -L $host -s -I --output /dev/null)
output=$(echo "$raw")


if [[ $output == *"200"* ]]
then
  	echo "OK - 200"
  	exit 0
else
	echo "ERROR - $raw - $host"
	exit 2
fi
