#!/bin/bash
API_URL=""
TOKEN=5

case "$1" in

"start")  echo "Starting Monitoring service checking."
    echo TODO $2
    ;;
"stop")  echo  "Stopping Monitoring service checking."
    echo TODO $2
    ;;
"reload")  echo  "Reloading services."
    echo TODO $2
    ;;
"list") echo  "Listing services."
    echo TODO
   ;;
*) echo "Command $1 is not processed"
   ;;
esac
