#!/bin/bash
used_space=`df -h / | grep -v Filesystem | awk '{print $5}' | sed 's/%//g'`

case $used_space in
100)
        echo "CRITICAL - $used_space% of disk space used."
        exit 2
  ;;
[1-6]*)
        echo "OK - $used_space% of disk space used."
        exit 0
  ;;
[7-8]*)
        echo "WARNING - $used_space% of disk space used."
        exit 1
  ;;
9[1-9])
        echo "CRITICAL - $used_space% of disk space used."
        exit 2
  ;;
*)
        echo "UNKNOWN - $used_space is undefined"
        exit 1
  ;;
esac

echo "CRITICAL - Case is kapot"
exit 420
