#!/bin/bash
timeout=5

while getopts ":H:t:" opt; do
  case $opt in
    H)     host=$OPTARG             ;;
    t)     timeout=$OPTARG          ;;
  esac
done


raw=$(timeout $timeout curl -m $timeout -L $host -s)
output=$(echo "$raw")


if [[ $output == "pong" ]]
then
  	echo "OK - pong"
  	exit 0
else 
	echo "ERROR - $raw - $host"
	exit 2
fi


# time=$(echo "$rawping" | tail -1| awk '{print $4}' | cut -d '/' -f 2)
# echo "time=$time;"
# #echo "error=PING FAILED;"

