#!/bin/bash
start=`date +%s.%N`
rawcheck=$(scripts/ssh mdeheij@42k.nl df -h | awk '{print $5}' | grep -v "Use%" | sed 's/%//' | head -n 1)
end=`date +%s.%N`
runtimems=$(echo "$end $start" | awk '{printf "%f", $1 - $2}')
mscontant=1000
runtime=$(echo "$runtimems * $mscontant" | bc)
echo "time=$runtime;"



if [[ ! ($rawcheck > 90)]]
then
  echo "status=ok;";
fi
echo "output=$rawcheck;"