#!/bin/bash

php checks/ping.php host=$1
# rawping=$(ping $1 -c 1 -w 1 -i 1)




# if [[ $rawping == *"1 received"* ]]
# then
#   echo "status=ok ";
# fi

# time=$(echo "$rawping" | tail -1| awk '{print $4}' | cut -d '/' -f 2)
# echo "time=$time;"

