#!/bin/bash
timeout=2

while getopts ":H:t:" opt; do
  case $opt in
    H)     host=$OPTARG             ;;
    t)     timeout=$OPTARG          ;;
  esac
done

rawping=$(ping $host -c 1 -w $timeout -i 1)

if [[ $rawping == *"1 received"* ]]
then
  	echo "OK - ping received"
  	exit 0
else
	echo "CRITICAL - $rawping"
	exit 2
fi
