#!/bin/bash
while getopts ":H:t:p:" opt; do
  case $opt in
    H)     host=$OPTARG             ;;
    t)     timeout=$OPTARG          ;;
    p)     port=$OPTARG          ;;
  esac
done


start=`date +%s.%N`

nmapAnswer=$(nmap -sU -p $port $host)
 
end=`date +%s.%N`
runtimems=$(echo "$end $start" | awk '{printf "%f", $1 - $2}')
mscontant=1000
runtime=$(echo "$runtimems * $mscontant" | bc)  
echo "time=$runtime;"


if [[ $nmapAnswer == *"open"* ]]
then
  echo "$nmapAnswer"
  exit 0
else 
  echo "ERROR"
  echo "$nmapAnswer"	
  exit 2
fi

